kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: es-retain
# provisioner: kubernetes.io/no-provisioner
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: Immediate