---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  accountserver.conf: |
    # Host/Port for the NATS Account Server
    http {
      host: "0.0.0.0"
      port: 9090
    }

    {{- with .Values.operator }}
    # Operator JWT used to validate the accounts.
    operatorjwtpath: "/etc/nats-config/operator/{{ .operatorjwt.configMap.key }}"

    # System Account JWT
    systemaccountjwtpath: "/etc/nats-config/sys/{{ .systemaccountjwt.configMap.key }}"
    {{- end }}

    {{- with .Values.nats }}
    # NATS Server connection
    nats {
      servers: [{{ .url }}]
      usercredentials: "/etc/nats-config/syscreds/{{ .credentials.secret.key }}"
    }
    {{- end }}

    {{- if eq .Values.store.type "file"}}
    store {
      dir: "/store"
    }
    {{- end }}
