# Should be created on production not as k8s.io/minikube-hostpath 
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: elastic-local-storage
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: WaitForFirstConsumer
parameters:
  volumetype: "replicate:3"