apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: default
  labels:
    app.kubernetes.io/component: elasticsearch
spec:
  selector:
    app.kubernetes.io/component: elasticsearch
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node