---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couch-data                          
  labels:
    volume: couch-data
spec:
  storageClassName: db-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /volume/logatron/couch-db/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couch-logs
  labels:
    volume: couch-logs
spec:
  storageClassName: db-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /volume/logatron/couch-db/logs
