apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    app.kubernetes.io/component: fluentd-logging
    version: v1
spec:
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.7-debian-elasticsearch7-1
        command: ["sh", "-c", "gem install fluent-plugin-http-healthcheck && fluentd -c /fluentd/etc/fluentd.conf "]
        ports:
        - name: http-input
          containerPort: 9880
          protocol: TCP
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-svc"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_UID
            value: "0"
          # X-Pack Authentication
          - name: FLUENT_ELASTICSEARCH_USER
            value: "elastic"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-user-password
                key: password
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 500m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/apps-logging/
        - name: fluentd-config
          mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/apps-logging/
      # Mapping local config
      - name: fluentd-config
        configMap:
          name: "fluentd-config-map"