apiVersion: v1
kind: Service
metadata:
  name: fluentd-svc
  namespace: default
  labels:
    app.kubernetes.io/component: fluentd-logging
spec:
  selector:
    app.kubernetes.io/component: fluentd-logging
  ports:
    - port: 9880
      name: http-input