---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
spec:
  selector:
    matchLabels:
      app: couch
  serviceName: couch-service
  replicas: 1
  template:
    metadata:
      labels:
        app: couch # pod label
    spec:
      containers:
      - name: couchdb
        image: couchdb:latest
        env:
        - name: NODE_NETBIOS_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODENAME
          value: $(NODE_NETBIOS_NAME).couch-service # FQDN in vm.args
        - name: COUCHDB_USER
          value: root
        - name: COUCHDB_PASSWORD
          value: N0T0uch
        - name: COUCHDB_SECRET
          value: monster
        - name: ERL_FLAGS
          value: "-name couchdb@$(NODENAME)"
        - name: ERL_FLAGS
          value: "-setcookie monster" #   the “password” used when nodes connect to each other.
        ports:
        - name: couchdb
          containerPort: 5984
        - name: epmd
          containerPort: 4369
        - containerPort: 9100
        volumeMounts:
          - name: couch-data-pvc
            mountPath: /opt/couchdb/data
          - name: couch-log-pvc
            mountPath: /opt/couchdb/logs
  volumeClaimTemplates:
  - metadata:
      name: couch-data-pvc
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          volume: couch-data
  - metadata:
      name: couch-log-pvc
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          volume: couch-logs